### ISSUE TITLE
Carousel broken when updating list

### ISSUE THREAD

**Issue by PulsarFox** [gs-shop/vue-slick-carousel#61] opened 2020-01-16 16:10 UTC
I have a VueSlickCarousel set on a component, and I want to dynamically add a new slide. 
The code is set this way 
```html
                  <VueSlickCarousel class="mb-2" v-bind="settings" ref="carousel">
                     <div v-for="(contact, IContact) in partenaire.contacts" :key="IContact">
                        <div>...</div>
                     </div>
                  </VueSlickCarousel>
```

Settings:
```
         settings: {
            arrows: true,
            slidesToShow: 1,
         }
```

When my `partenaire.contacts` list has more than 1 element at the beginning, everything works fine, it adds a new slide and it fits at the end of the Carousel. It doesn't updates the dots when the settings dots is set though. 

The problem is when I have only one element at the beginning, and I want to add more dyamically : the arrows aren't set, and the carousels adds a row in a weird way... I didn't manage to find a way to manually refresh the component either.

Some screens : 

Working fine : 
![image](https://user-images.githubusercontent.com/18594651/72541478-e2c9c780-3882-11ea-87c8-a0b89d4269b6.png)

Broken when adding: 
(I slided the carousel a little bit on the right for more visibility, also don't mind the top right artifact)
![image](https://user-images.githubusercontent.com/18594651/72541532-fb39e200-3882-11ea-8304-14cf655c489d.png)

**Comment by PulsarFox** [comment] 2020-01-16 16:36
I have managed to hack a fix by changing the settings this way on array change

```
               this.settings.slidesToShow = 2;
               this.$nextTick(() => {
                  this.settings.slidesToShow = 1;
               })
```

**Comment by kyuwoo-choi** [comment] 2020-01-17 02:26
thanks for the reporting. adding an example I can produce the problem will help me into it quicker.

**Comment by kyuwoo-choi** [comment] 2020-02-06 23:20
I'm closing this due to the lack of example I can reproduce.
please reopen this with steps/examples.

**Closed by kyuwoo-choi** 2020-02-06 23:20 UTC
Labels: bug

**Comment by Cel51** [comment] 2020-03-10 09:11
[Demo error link](https://nuxt-slicker-carousel.herokuapp.com/)
[Git to reproduce](https://github.com/Cel51/nuxt-slick-carousel)

The app as a store, when switching pages from 1 to another, the count is modified from 4 on the "home" page to the about page (then to 1). The carousel is inside a layout (initialized once on the load of the app). When browsing from one page to another, the total amout of slide change (is updated) (see here for the carousel)[https://github.com/Cel51/nuxt-slick-carousel/blob/master/layouts/default.vue] 

The component is not updating the total amout of slide when browsing from the about (1 slide) to the homepage (4 slide) causing trouble and preventing slide and when we attempt to slide, it cause a visual bug.

**Comment by Cobertos** [comment] 2020-10-19 10:52
I had the same issue. Took me hours to debug. Really wish this would be more explicitly called out as a limitation.
